# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'Backend'

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Provide reason behind manual action run'
        required: true
        type: 'string'
  push:
    paths:
    - 'Backend/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'Backend/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'self-hosted'
    steps:
    - name: 'Checkout repository'
      uses: 'actions/checkout@v3'

    - name: 'Setup .NET'
      uses: 'actions/setup-dotnet@v3'
      with:
        dotnet-version: '8.x'

    - name: 'Restore dependencies'
      run: 'dotnet restore'
      working-directory: 'Backend'

    - name: 'Build'
      run: 'dotnet build --no-restore'
      working-directory: 'Backend'

    - name: 'Test'
      run: 'dotnet test --logger trx --no-build --verbosity normal'
      working-directory: 'Backend'

    - name: 'Setup Python' # For publish test results
      uses: 'actions/setup-python@v5'
      with:
        python-version: 3.8

    - name: 'Publish Test Results'
      uses: 'EnricoMi/publish-unit-test-result-action@v2'
      if: always()
      with:
        files: |
          Backend/**/*.trx

    - name: 'Deploy Application'
      run: |
        dotnet publish --runtime linux-arm64 --self-contained -c production WebApi
        ./deploy.sh
      working-directory: 'Backend'
      # Do not run deployment from PR
      if: github.event_name != 'pull_request'
