# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: 'Documentation'

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Provide reason behind manual action run'
        required: true
        type: 'string'
  push:
    paths:
    - 'Documentation/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'Documentation/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'self-hosted'
    steps:
    - name: 'Checkout repository'
      uses: 'actions/checkout@v3'

    - name: 'Build'
      # Glossaries https://tex.stackexchange.com/a/46732
      # Run build twice https://texfaq.org/FAQ-rerun
      run: |
        pdflatex thesis.tex
        biber thesis
        makeglossaries thesis
        pdflatex thesis.tex
        pdflatex thesis.tex
        pdflatex thesis.tex
        pdflatex thesis.tex
      working-directory: 'Documentation'

    - uses: actions/upload-artifact@v3
      with:
        name: 'thesis.pdf'
        path: 'Documentation/thesis.pdf'

    - name: 'Deploy Documentation'
      run: |
        cp thesis.pdf /opt/city-planner-documentation/${{ github.event_name == 'pull_request' && format('{0}.pdf', github.sha) || 'thesis.pdf' }}
      working-directory: 'Documentation'

    - name: 'Create comment'
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: ${{ github.event.number }}
        body: |
            Preview of thesis at latest HEAD avliable at: [https://city-planner.budziszm.pl/thesis/${{ github.sha }}](https://city-planner.budziszm.pl/thesis/${{ github.sha }})
      # Comment only on PR
      if: github.event_name == 'pull_request'
