# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Backend

on:
  workflow_call:
    inputs:
      reason:
        description: 'Provide reason behind manual action run'
        required: true
        type: string
  push:
    paths:
    - 'Backend/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'Backend/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: 'Backend'
    - name: Build
      run: dotnet build --no-restore
      working-directory: 'Backend'
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: 'Backend'
