# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 'Frontend'

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Provide reason behind manual action run'
        required: true
        type: 'string'
  push:
    paths:
    - 'Frontend/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'Frontend/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'self-hosted'
    steps:
    - name: 'Checkout repository'
      uses: 'actions/checkout@v3'

    - name: 'Setup pnpm'
      uses: 'pnpm/action-setup@v2'
      with:
        version: 8

    - name: 'Use Node.js 20'
      uses: 'actions/setup-node@v3'
      with:
        node-version: '20.x'
        cache: 'pnpm'
        cache-dependency-path: 'Frontend/pnpm-lock.yaml'

    - name: 'Restore packages'
      run: |
        pnpm config set store-dir $RUNNER_TOOL_CACHE/.pnpm
        pnpm i --frozen-lockfile
      working-directory: 'Frontend'

    - name: 'Lint files'
      run: 'pnpm ng lint'
      working-directory: 'Frontend'

    - name: 'Run unit tests'
      run: 'pnpm ng test --watch=false --code-coverage --reporters=junit,coverage'
      working-directory: 'Frontend'
      env:
        CHROME_BIN: '/usr/bin/chromium-browser'

    - name: 'Setup Python' # For publish test results
      uses: 'deadsnakes/action@v3.1.0'
      with:
        python-version: 3.8

    - name: 'Publish Test Results'
      uses: 'EnricoMi/publish-unit-test-result-action/composite@v2'
      if: always()
      with:
        files: |
          Frontend/coverage/**/TESTS*.xml

    # - name: 'Publish Coverage Report'
    #   uses: 'romeovs/lcov-reporter-action@v0.2.16'
    #   with:
    #     lcov-file: 'Frontend/coverage/lcov.info'

    - name: 'Build Application'
      run: 'pnpm build'
      working-directory: 'Frontend'

    - name: 'Deploy Application'
      run: './deploy.sh'
      working-directory: 'Frontend'
      # Do not run deployment from PR
      if: github.event_name != 'pull_request'
