# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: 'Frontend'

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Provide reason behind manual action run'
        required: true
        type: 'string'
  push:
    paths:
    - 'Frontend/**'
    branches: [ "main" ]
  pull_request:
    paths:
    - 'Frontend/**'
    branches: [ "main" ]

jobs:
  build:
    runs-on: 'self-hosted'
    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'pnpm/action-setup@v2'
      with:
        version: 8

    - name: 'Use Node.js 20'
      uses: 'actions/setup-node@v3'
      with:
        node-version: '20.x'
        cache: 'pnpm'
        cache-dependency-path: 'Frontend/pnpm-lock.yaml'

    - run: |
        pnpm config set store-dir $RUNNER_TOOL_CACHE/.pnpm
        pnpm i --frozen-lockfile
      working-directory: 'Frontend'

    - run: 'pnpm ng test --watch=false --code-coverage --reporters=junit,coverage'
      working-directory: 'Frontend'
      env:
        CHROME_BIN: '/usr/bin/chromium-browser'

    - name: 'Publish Test Results'
      uses: 'EnricoMi/publish-unit-test-result-action@v2'
      if: always()
      with:
        files: |
          Frontend/coverage/**/TESTS*.xml

    - name: 'Display coverage'
      uses: 'ewjoachim/coverage-comment-action@v1'
      with:
        COVERAGE_FILE: 'Frontend/coverage/cobertura-coverage.xml'
        GITHUB_TOKEN: ${{ github.token }}

    - run: 'pnpm build'
      working-directory: 'Frontend'

    - run: 'bash Frontend/deploy.sh'
      # Do not run deployment from PR
      if: github.event_name != 'pull_request'
